CREATE SCHEMA IF NOT EXISTS academic;
CREATE SCHEMA IF NOT EXISTS admin;
CREATE SCHEMA IF NOT EXISTS library;
CREATE SCHEMA IF NOT EXISTS finance;
CREATE SCHEMA IF NOT EXISTS student_life;
CREATE SCHEMA IF NOT EXISTS system;
